administrator-manual/en/release_notes.rst
administrator-manual/it/release_notes.rst

I'd like to add also a deprecation warning for ``php/DateTimezone`` prop. What do you think?

Added PHP date.timezone note for 6.6 release. Refs #3016 #3068

---

administrator-manual/en/shared_folder.rst
administrator-manual/it/shared_folder.rst

The old Shared Folders page was a copy of the online manual page. This is a complete review, including .htwritable, .htaccess feature explanation.

Shared folders (en, it)

---

developer-manual/en/templates.rst

change in line 293 undone: Link not displayed properly within ReadTheDocs.
Markdown link replaced with a :ref: placeholder.

typos - text formatting: undo change in line 293

---

developer-manual/en/gateway.rst

Some notes on how to add a fragment in the shorewall rule

added the template fragment way in shorewall rules

---

developer-manual/en/nethserver-dc.rst

DC factory resetresult in Start DC  unclickable:
config show nsdc
gives:
nsdc=service
IpAddress=1.2.3.4
bridge=br0
status=enabled
then:
config setprop nsdc status disabled
will set nsdc status to disabled and new start is possible.
I hope this will help others. Cheers

"DC factory reset" fix

---

administrator-manual/en/accounts.rst

- Use "domain admins" as default group
- Remove references to "administrators"
NethServer/dev#5209

Group "administrators" no longer available

---

administrator-manual/en/nextcloud.rst

It is to inform the user that he must re-enable the apps after an update/upgrade process.

nextcloud: add note for upgrade process

---

administrator-manual/en/shared_folder.rst

Since `fstab` template has been removed, the user should take core of enabling ACL if needed.
I didn't add the requirements inside the install section because the option can be enabled after install.
NethServer/dev#5490

admin manual: ACL for shared folders

---

administrator-manual/en/vpn.rst

You have an error in the template expansion of IPSEC tunnel if one green NIC is not found, this is not implicit and must be written in documentation that you must have red and green interface to use IPSEC tunnel
https://community.nethserver.org/t/blank-dropdown-in-ipsec-tunnel/9894/4

Specify the gateway mandatory configuration to use IPSEC

---

administrator-manual/en/backup.rst

Corrected prop name, otherwise getting error:
>Use of uninitialized value $login in concatenation (.) or string at /etc/e-smith/events/actions/mount-cifs line 67.
Related to https://github.com/NethServer/docs/pull/347

typo (SMBUser/SMBLogin)

---

administrator-manual/en/sogo.rst

Adapt the documentation to the single vhost capability.

VirtualHosts is for a single sogo vhost

---

administrator-manual/en/sogo.rst
administrator-manual/en/webtop5.rst

NethServer/dev#5575
- With the introduction of the SOGo-panel precedence changed.
- discourage to keep Webtop and SOGo installed on the long run.

ActiveSync SOGo takes precedence

---

administrator-manual/en/accounts.rst

A mistake in `signal-event` command, it was written without the `-` character.

Fix command mistake

---

administrator-manual/en/webtop5.rst

Removed note on CalDAV and CardDAV, added the possibility to transform images from public link and correct the reference to the impersonate for modifying domain mailcard

Update WebTop 5 docs

---

administrator-manual/en/webtop5.rst

Correct typing error and add two paragraph:
- Hide auto-suggested recipient in lookups
- Edit subject of a mail and save it

Update webtop5 chapter

---

administrator-manual/en/accounts.rst

Posix ACLs support for NSDC is an hidden requirement to make GPOs work
NethServer/dev#5733

Require Posix ACLs for NSDC

---

administrator-manual/en/nscom_releases.rst
administrator-manual/en/release_notes.rst

https://github.com/NethServer/dev/issues/5831

Release notes 7.7

---

administrator-manual/en/base_system.rst
administrator-manual/en/base_system2.rst

Avoid the word "firewall", it sounds out of context here.

Rewording Network service definition

---

administrator-manual/en/hotsync.rst
administrator-manual/en/index.rst

Hotsync is going to be moved to NethForge and supported by community.
NethServer/dev#5996

Move hotsync only to community

---

administrator-manual/en/disaster_recovery.rst

This is a draft procedure to restart the nsdc service after a "skip network" restore. I need to test it.
https://github.com/NethServer/dev/issues/6099

Samba AD restart after skip network

---

administrator-manual/en/backup_customization.rst

The rsync script does not support `--fake-super` option.

backup: add note for rsync

---

administrator-manual/en/conf.py

The Sphinx theme uses angular quotes (e.g. «Benvenuto») and are not good in Italian.
See also https://github.com/nethesis/nethvoice-docs/pull/67

Disable smartquotes in nsent

---

administrator-manual/en/blacklist.rst

DNS blacklist does not work for host proxied with web proxy. We cannot specify on `squid.conf` a custom port (the `pihole` one) to `dns_nameservers` prop.
We can eventually add on `/etc/dnsmasq.conf` the attribute `addn-hosts` with the dns blacklist to correctly block domains. For example:
```
...
addn-hosts=/path/to/dns/blacklists.dns
...
```
But this method and some quirks (redirection on nethserver launcher i.e.), and it's not a valid alternative.
We simply decided to document that this feature is currently unavailable
Nethserver/dev#6212

docs. update blacklist chapter

---

administrator-manual/en/base_system2.rst
administrator-manual/en/index.rst
administrator-manual/en/mail.rst

The Email page still refers to the old Server Manager UI. We added many features and changed some UI labels. This PR is to align the documentation with the new UI.
https://github.com/NethServer/dev/issues/6247

Fix Email page for Cockpit Server Manager

---

administrator-manual/en/upgrade.rst

The in-place upgrade method is stable since months.
See also https://github.com/NethServer/docs/pull/469

Remove in-place "beta" wording

---

administrator-manual/en/index.rst
administrator-manual/en/phonebook-mysql.rst

This module should be visible inside the index,
because it is still supported and updated

phonebook: move to modules section

---

administrator-manual/en/release_notes.rst

Update from NC 19 to 20 doesn't break theming anymore:
Upstream seems to have released a fix for it.

releases_notes: update nextcloud note

---

administrator-manual/en/subscription.rst

We can now enable extra repositories by the command line for the superscription
NethServer/dev#6427

Enable extra repositories by the CLI in subscription

---

administrator-manual/en/nsent/_static/nethesis.css

The bulleted list is now represented by squares and is no longer empty

NethServer_Ent: fixed missing point in bulleted list

---

administrator-manual/en/dhcp.rst

Fix the disable tftp part, it's dnsmasq instead of dhcp.
See https://community.nethserver.org/t/cant-open-directory-etc-e-smith-events-nethserver-tftp-save/19010
Thanks to fausp

Fix disable tftp in dhcp.rst

---

administrator-manual/en/collabora.rst

In the new version the service name changed from loolwsd to coolwsd and the config tool from loolconf to coolconf.
When using a remote Nextcloud instance, it may need a reboot after Collabora update.
The admin panel URL changed.
NethServer/dev#6607

Add update reboot hint and name changes

---

administrator-manual/en/nscom/requirements.txt
administrator-manual/en/nsent/requirements.txt

To avoid problems related to the UI the version of ```sphinx_rtd_theme``` goes from 0.5 to 1.0

Updated Sphinx_rtd_theme at the latest compatible version

---

administrator-manual/en/docker.rst

Fix a typo and add "published" to clarify that only published ports of containers are opened instead of the containers itself.
https://community.nethserver.org/t/nethserver-firewall-assigns-net-interface-to-docker-network/20176/5

Fix typo and clarify published ports

---

administrator-manual/en/base_system.rst
administrator-manual/en/web_proxy.rst

We need to change the `rm` command into the `Disable Let's Encrypt` section. If we remove all the content of the path `/etc/letsencrypt/` we loose the `/etc/letsencrypt/renewal-hooks/deploy/10nethserver` script, too. This deletion make the system unable to put in production a new LE certificate.
We also need to change the `find` command used to delete the older `lightsquid` reports.

Update base_system.rst and web_proxy.rst
