administrator-manual/en/release_notes.rst
administrator-manual/it/release_notes.rst

http://dev.nethserver.org/issues/3026

Release notes: Differentiate root and admin users. Refs #3026

---

administrator-manual/it/base_system.rst
developer-manual/en/events.rst

New trusted-networks-update event. Refs #3195

---

administrator-manual/it/nethserver-enterprise/hotspot.rst

Update server requirements

---

administrator-manual/en/base_system.rst
administrator-manual/en/firewall.rst

Changes related to issue #3218

PPPoE administrator manual update

---

administrator-manual/en/access.rst
administrator-manual/it/access.rst

Change requested here
http://community.nethserver.org/t/user-and-groups-isnt-in-visible-in-the-menu/2223/4

Explicit module list to see Users and groups

---

administrator-manual/en/firewall.rst
administrator-manual/it/firewall.rst

Updated the admin's manual with new Firewall rules page capability

Policy rules interface. Refs #2809

---

administrator-manual/en/vpn.rst

See http://dev.nethserver.org/issues/3326

IPsec tunnels: Support for %any in Remote IP field

---

administrator-manual/it/vpn.rst

Support for %any in Remote IP field [italiano]

IPsec tunnels %any. Refs #3326

---

developer-manual/en/introduction.rst

line 12: replaced 'avout' with 'about'
line 29: changed wording order ('free feel' replaced with 'feel free')

minor language correction

---

administrator-manual/en/adagios.rst
administrator-manual/en/ocs.rst
administrator-manual/it/adagios.rst
administrator-manual/it/ocs.rst

Adagios and OCS Inventory man pages first release

adding Adagios and OCS Inventory man pages

---

administrator-manual/en/ocs.rst
administrator-manual/it/adagios.rst
administrator-manual/it/ocs.rst

fixed some typos and added link to agent software page

Updated Adagios and OCS man pages

---

administrator-manual/en/backup.rst
administrator-manual/it/backup.rst

backup-data restore docs. Refs NethServer/dev#5108

---

developer-manual/en/templates.rst

added lines with the discripton of expanding templates

Update templates.rst with discripton of expanding templates

---

administrator-manual/en/accounts.rst

Added Admin account section NethServer/dev#5157

---

administrator-manual/en/installation.rst
administrator-manual/en/installation_centos_end.inc
administrator-manual/en/installation_end.inc
administrator-manual/en/installation_interactive_end.inc

Add Manual install mode section

---

administrator-manual/en/base_system.rst

* Fix typo.
* Deleted reference to Roaming Profiles (please, verify if correct)

Unsure: roaming profiles on NethServer 7?

---

administrator-manual/en/conf.py
administrator-manual/en/hotspot.rst
administrator-manual/en/index.rst
administrator-manual/en/nethcti_intro.rst
administrator-manual/en/nethvoice_intro.rst
administrator-manual/en/phonebook-mysql.rst
administrator-manual/en/registration.rst
administrator-manual/en/weekly_report.rst

conf.py: hide enterprise modules when building community manual

Import enterprise modules

---

administrator-manual/en/migration.rst
administrator-manual/en/nextcloud.rst

Update Migration section

---

administrator-manual/en/packages.rst

Added automatic update hint for Enterprise version;
Removed software center removal option for installed packages for
Enterprise version.

Modified packages rst

---

developer-manual/en/mysql.rst

nice cut and paste but inaccurate for nethserver ;)

/var/lib/nethserver/secrets/mysql

---

administrator-manual/en/migration.rst

Accounts provider migration scenarios

---

administrator-manual/en/index.rst
administrator-manual/en/webtop5.rst

Add webtop5 chapter

---

administrator-manual/en/index.rst

Firewall entry incorrectly compares twice

---

administrator-manual/en/accounts.rst

New SssdConfig page documentation

---

administrator-manual/en/accounts.rst
administrator-manual/en/backup.rst
administrator-manual/en/migration.rst
administrator-manual/en/packages.rst
administrator-manual/en/shared_folder.rst
administrator-manual/en/upgrade.rst
administrator-manual/en/virtual_hosts.rst

NS 6 upgrade fixes

---

administrator-manual/en/upgrade.rst

Admin manual: add note for Samba classic upgrade

---

administrator-manual/en/upgrade.rst

Disable ntlm auth reminder

---

administrator-manual/en/web_proxy.rst
developer-manual/en/nethserver-nextcloud.rst
developer-manual/en/nethserver-squid.rst

Add bypass by domains documentation

---

administrator-manual/en/access.rst
administrator-manual/en/backup.rst
administrator-manual/en/base_system.rst
administrator-manual/en/mail.rst

New backup history and restore wizard UI

---

administrator-manual/en/vpn.rst

Admin manual: update VPN chapter

---

administrator-manual/en/web_proxy.rst

Admin manual: add squid rules

---

administrator-manual/en/accounts.rst

Change DC IP address notes

---

administrator-manual/en/installation.rst

As per http://community.nethserver.org/t/v7-3-1611-installation-doesnt-work/7185/13

tools to write the USB stick

---

administrator-manual/en/webtop5.rst

Admin manual: WebTop 5 import PST

---

administrator-manual/en/release_notes.rst

Release notes 7.4: samba DC changes

---

administrator-manual/en/conf.py
administrator-manual/en/index.rst
administrator-manual/en/nscom_releases.rst
administrator-manual/en/release_notes.rst

To remove this:
https://github.com/NethServer/dev/blob/35214e511dd739b7e43c66d7b4221f1f256e87a9/releases.md

Add NS7 ISO releases index

---

administrator-manual/en/suricata.rst

admin manual: add new suricata rule categories

---

administrator-manual/en/mail.rst

Describe the "Accept unknown recipients" option

---

administrator-manual/en/accounts.rst

Users and groups: renamed UI field

---

administrator-manual/en/hotsync.rst
administrator-manual/en/index.rst

Add HotSync administrator manual

---

administrator-manual/en/.tx/config
administrator-manual/en/index.rst
administrator-manual/en/locale/es/LC_MESSAGES/ui.po
administrator-manual/en/locale/it/LC_MESSAGES/ui.po
administrator-manual/en/shared_folder.rst
administrator-manual/en/ui/FileServer.rst

Windows file server page reference and guide

---

administrator-manual/en/index.rst
administrator-manual/en/sogo.rst
administrator-manual/en/webtop5.rst

Ported from: https://wiki.nethserver.org/doku.php?id=sogo&s[]=sogo
- Removed references to NS 6 since the manual is only for NS 7
- Refactor for RST syntax

Add SOGo chapter

---

administrator-manual/en/sogo.rst

Removed myself as maintainer, we could drop a note in the wiki
Adjust the nightly mirror to sogo3

Minor adjustments

---

developer-manual/en/building_rpms.rst

Added set up step for release-tag command

---

administrator-manual/en/index.rst
administrator-manual/en/mail2.rst

Add Email 2 module page (beta)

---

administrator-manual/en/conf.py
administrator-manual/en/nsent/robots.txt

Disable web crawlers in robots.txt

---

administrator-manual/en/mail2.rst
administrator-manual/en/pop3_connector.rst

Add getmail documentation for Email 2 module

---

administrator-manual/en/base_system.rst

admin manual: how to disable LE

---

administrator-manual/en/mail2.rst
administrator-manual/en/pop3_connector.rst
administrator-manual/en/pop3_proxy.rst

POP3 proxy 2 (Beta) documentation

---

administrator-manual/en/upgrade.rst

Change the instructions according to the `rsync-upgrade` command output

Fix rsync upgrade procedure

---

administrator-manual/en/mail2.rst

Rspamd web UI authentication

---

administrator-manual/en/hotsync.rst

Use nethserver-hotsync-save event

---

administrator-manual/en/nextcloud.rst

Nextcloud: add custom virtual host and 1 note

---

administrator-manual/en/.tx/config
administrator-manual/en/index.rst
administrator-manual/en/tlspolicy.rst
administrator-manual/en/ui/TlsPolicy.rst

Add TLS policy section and UI reference

---

administrator-manual/en/upgrade.rst

- The home dir reset permission is now automatic
- Document the IP conflict case
NethServer/dev#5432

Fix ns6upgrade procedure

---

administrator-manual/en/migration.rst

https://github.com/NethServer/dev/issues/5447

List reserved AD account names

---

administrator-manual/en/upgrade.rst

Exclude guest and administrator from ns6upgrade

---

README.rst
administrator-manual/en/hotsync.rst

Added package needed to build documenation to README file;
Added conditional section for module installation in hotsync page.

Modified readme and hotsync files

---

administrator-manual/en/tlspolicy.rst

Fix TLS policy identifiers, Postfix notes

---

administrator-manual/en/team_chat.rst
developer-manual/en/modules
developer-manual/en/nethserver-mattermost.rst

Move sync command to developer manual.

Update Mattermost doc

---

administrator-manual/en/mail2.rst

https://github.com/NethServer/dev/issues/5452

Email 2 upgrade for disclaimer component

---

administrator-manual/en/fax_server.rst

admin manual: add warning to mail2fax

---

administrator-manual/en/access.rst

Add Session timeouts section

---

administrator-manual/en/conf.py

Update link download ISO for Enterprise

Update link download ISO

---

developer-manual/en/package_groups.rst

Updated for automated comps build on Travis
https://github.com/nethesis/nethinfra/issues/28

dev: automated builds for package groups

---

administrator-manual/en/proxy_pass.rst
administrator-manual/en/ui/ProxyPass.rst

Add ProxyPass (Reverse proxy) page

---

administrator-manual/en/fail2ban.rst
administrator-manual/en/index.rst

https://github.com/NethServer/dev/issues/5489

Fail2ban documentation

---

administrator-manual/en/firewall.rst

Admin manual: complex traffic shaping

---

administrator-manual/en/installation.rst

admin manual: installer known issues

---

administrator-manual/en/nscom_releases.rst
administrator-manual/en/release_notes.rst

Draft 7.5.1804 beta ISO release

---

administrator-manual/en/subscription.rst
developer-manual/en/events.rst

Ns release lock

---

administrator-manual/en/packages.rst
administrator-manual/en/release_notes.rst
administrator-manual/en/subscription.rst

New Software center guide

---

administrator-manual/en/installation.rst

The issue is now fixed from the kickstart.

admin manual: remove rtc known issue

---

administrator-manual/en/tlspolicy.rst

Add note about default TLS policy 20180330

---

administrator-manual/en/base_system.rst
administrator-manual/en/tlspolicy.rst

Describe TLS policy 2018-06-21

---

administrator-manual/en/webtop5.rst

Please correct me if i do not follow the right procedure!
Its a small change which is in the docs for a solution which already is in place for a long time now
see:
https://community.nethserver.org/t/conflict-between-webtop-and-sogo/10258/3

Webtop is the main group-ware solution, hence it has preference

---

administrator-manual/en/sogo.rst
administrator-manual/en/webtop5.rst

https://github.com/NethServer/nethserver-sogo/pull/27

nethserver-sogo accompanying PR#27

---

administrator-manual/en/ui/Ejabberd.rst

https://github.com/NethServer/dev/issues/5537

Ejabberd UI documentation section

---

administrator-manual/en/webtop5.rst

Ready for the final review @filippocarletti 
Please squash everything before merging.

Webtop webdav

---

administrator-manual/en/backup.rst

Some words and db props corrections.

typos (NFShare/NFSShare)

---

administrator-manual/en/chat.rst

Documentation update for ejabberd

---

administrator-manual/en/sogo.rst
administrator-manual/en/ui/SOGo.rst

the online help page of sogo in the server-manager
https://github.com/NethServer/dev/issues/5575

SOGo help online

---

administrator-manual/en/ui/SOGo.rst

Notifications help
Single vhost help

Notification and single apache vhost

---

administrator-manual/en/backup.rst
administrator-manual/en/hotsync.rst

Added line for custom inclusion in backup-config.
Changed hotsync module installation command for slave.

Updated backup.rst and hotsync.rst

---

administrator-manual/en/tlspolicy.rst

https://github.com/NethServer/dev/issues/5580

Add the tlsPolicy 2018-10-01

---

administrator-manual/en/mail.rst
administrator-manual/en/mail2.rst
administrator-manual/en/pop3_connector.rst
administrator-manual/en/pop3_proxy.rst

Clean up references to obsoleted manual procedures.
NethServer/dev#5589

Automatic upgrade to Rspamd

---

administrator-manual/en/mail2.rst

https://github.com/NethServer/dev/issues/5605
@DavidePrincipi @gsanchietti how to remove to the old antispam engine

Documentation on old anti-spam removal

---

administrator-manual/en/index.rst
administrator-manual/en/mail.rst
administrator-manual/en/rspamd.rst

Add a documentation on rspamd @DavidePrincipi

rspamd documentation

---

administrator-manual/en/mail.rst

https://github.com/NethServer/dev/issues/5597
@DavidePrincipi the readthedoc documentation

Quarantine documentation

---

administrator-manual/en/.tx/config
administrator-manual/en/index.rst
administrator-manual/en/upgrade_tool.rst

Add ns6 upgrade tool (beta) section

---

administrator-manual/en/backup.rst

backup: remove NotifyFrom

---

administrator-manual/en/upgrade_tool.rst

Add "Post upgrade checklist" section

---

administrator-manual/en/upgrade_tool.rst

Add Upgrade to Active Directory section

---

administrator-manual/en/upgrade_tool.rst

Check the installed modules

---

administrator-manual/en/accounts.rst

https://github.com/NethServer/dev/issues/5657

Admin script to delete users

---

administrator-manual/en/accounts.rst

accounts: fix delete_users path

---

administrator-manual/en/web_proxy.rst

@gsanchietti I used your comment that we can find at https://github.com/NethServer/dev/issues/5662#issuecomment-442150472

Logrotate setting in squid

---

administrator-manual/en/upgrade_tool.rst

Upgrade tool beta 2

---

administrator-manual/en/firewall.rst

Improve NDPI section

---

administrator-manual/en/accounts.rst

account: improve user delete section

---

administrator-manual/en/hotsync.rst
administrator-manual/en/phonebook-mysql.rst

`nethserver-cockpit-hotsync` module ref have to be removed
added NS 6.x ref for SOGo contacts import feature

Update hotsync.rst and phonebook-mysql.rst

---

administrator-manual/en/conf.py
administrator-manual/en/nscom_releases.rst
administrator-manual/en/release_notes.rst

This is a work-in progress, please add your notes! /cc @NethServer/dev_team

NethServer 7.6 release notes 

---

administrator-manual/en/virtual_machines.rst

Enable groups in yum command

---

administrator-manual/en/backup.rst

Remove single backup

---

administrator-manual/en/upgrade.rst

Added conditional upgrade-tool reference to upgrade page.

Added upgrade-tool reference

---

administrator-manual/en/upgrade.rst

Fixed restore-data command typo and added a note

Updated upgrade page

---

administrator-manual/en/backup.rst
administrator-manual/en/installation.rst
administrator-manual/en/migration.rst
administrator-manual/en/upgrade.rst

Added the command to run backup from shell and the explicit reference to use always the latest ISO for installation/upgrade/migration

Updated backup.rst, installation.rst, upgrade.rst and migration.rst

---

administrator-manual/en/packages.rst
administrator-manual/en/release_notes.rst

Remove software updates origin policy

---

administrator-manual/en/locale/es/LC_MESSAGES/backup.po
administrator-manual/en/locale/es/LC_MESSAGES/installation.po
administrator-manual/en/locale/es/LC_MESSAGES/migration.po
administrator-manual/en/locale/es/LC_MESSAGES/packages.po
administrator-manual/en/locale/es/LC_MESSAGES/release_notes.po
administrator-manual/en/locale/es/LC_MESSAGES/upgrade.po
administrator-manual/en/locale/es/LC_MESSAGES/webtop5.po
administrator-manual/en/locale/it/LC_MESSAGES/backup.po
administrator-manual/en/locale/it/LC_MESSAGES/installation.po
administrator-manual/en/locale/it/LC_MESSAGES/migration.po
administrator-manual/en/locale/it/LC_MESSAGES/packages.po
administrator-manual/en/locale/it/LC_MESSAGES/release_notes.po
administrator-manual/en/locale/it/LC_MESSAGES/subscription.po
administrator-manual/en/locale/it/LC_MESSAGES/upgrade.po
administrator-manual/en/locale/it/LC_MESSAGES/webtop5.po

Pull strings from Transifex

---

administrator-manual/en/virtual_machines.rst

Community and Enterprise installation commands are different.

Updated virtual_machine rst

---

administrator-manual/en/accounts.rst

Modified password expiration paragraph

Updated accounts rst

---

administrator-manual/en/backup.rst

Please help me improve the warning!

backup: restore on the same version

---

administrator-manual/en/nextcloud.rst

Add nextcloud 16

---

administrator-manual/en/mail.rst

Use IP-based SMTP access as last resort

---

administrator-manual/en/mail.rst

Email. Visibility internal UI label

---

administrator-manual/en/mail.rst

Cockpit new features

---

administrator-manual/en/mail.rst
administrator-manual/en/mail2.rst
administrator-manual/en/pop3_connector.rst
administrator-manual/en/pop3_proxy.rst
administrator-manual/en/rspamd.rst

Email. Fix anti-virus dash

---

administrator-manual/en/shared_folder.rst

Add smbaudit

---

administrator-manual/en/installation.rst

https://github.com/nethesis/dev/issues/5680

install: new go.nethesis.it procedure

---

README.rst
administrator-manual/en/.tx/config
administrator-manual/en/index.rst
administrator-manual/en/report.rst

Doc page for Report module (Dante)

Report module (Dante)

---

administrator-manual/en/backup.rst

Modified disaster recovery procedure
https://github.com/NethServer/dev/issues/5794

Updated backup.rst

---

administrator-manual/en/installation.rst

See https://github.com/nethesis/nethesis.github.io/pull/3
Refs nethesis/dev#5680

Fix CentOS install procedure

---

administrator-manual/en/installation.rst
administrator-manual/en/locale/es/LC_MESSAGES/backup.po
administrator-manual/en/locale/es/LC_MESSAGES/installation.po
administrator-manual/en/locale/es/LC_MESSAGES/report.po
administrator-manual/en/locale/it/LC_MESSAGES/backup.po
administrator-manual/en/locale/it/LC_MESSAGES/installation.po
administrator-manual/en/locale/it/LC_MESSAGES/report.po

Fast-track docs updates for the install on CentOS procedure
Merge notes: use rebase-merge strategy

Cherry pick go.nethesis.it

---

administrator-manual/en/webtop5.rst

Update stable branch

---

administrator-manual/en/index.rst
administrator-manual/en/launcher.rst
administrator-manual/en/report.rst

Documentation for Nethesis Launcher

Documentation for Nethesis Launcher

---

administrator-manual/en/index.rst
administrator-manual/en/launcher.rst

Documentation for Nethesis Launcher (#443)

---

administrator-manual/en/sogo.rst
administrator-manual/en/webtop5.rst

New WebTop ActiveSync implementation

---

administrator-manual/en/tlspolicy.rst

https://github.com/NethServer/dev/issues/5835

Clean up OpenSSH in TLS policy page

---

administrator-manual/en/packages.rst
administrator-manual/en/packages_legacy.rst

Old software center has been moved to packages_legagcy.rst chapter.

Add new software center

---

administrator-manual/en/backup.rst
administrator-manual/en/backup_customization.rst
administrator-manual/en/backup_legacy.rst
administrator-manual/en/base_system2.rst
administrator-manual/en/conf.py
administrator-manual/en/disaster_recovery.rst
administrator-manual/en/index.rst

Split into 4 chapters:
- backup
- disaster recovery
- backup customization
- legacy backup

Refactor backup chapter

---

administrator-manual/en/firewall.rst
administrator-manual/en/firewall2.rst

Integration to existing firewall documentation.

Add cockpit firewall chapter

---

administrator-manual/en/locale/it/LC_MESSAGES/backup.po
administrator-manual/en/locale/it/LC_MESSAGES/release_notes.po

Pull Italian translations from Transifex

---

administrator-manual/en/disaster_recovery.rst

- fix title
- fix duplication of "NethServer Enterprise Enterprise"

Fix typos on disaster recovery

---

administrator-manual/en/disaster_recovery.rst

Added explicit reference to backup-data name.
Fixed broken reference.

Edited disaster_recovery.rst

---

administrator-manual/en/phone_home.rst

See NethServer/nethserver-phonehome#8

phone-home: add  type metric

---

administrator-manual/en/chat.rst

https://github.com/NethServer/dev/issues/5934
[skip ci]

Jabberadmins group usage clarification

---

administrator-manual/en/base_system2.rst

delegation: terminal can't be delegated

---

administrator-manual/en/mail.rst

This is a clarification of the Allow/Block rules functioning after the release of 
- https://github.com/NethServer/dev/issues/5940
- https://github.com/NethServer/dev/issues/5951

Clarify Allow/Block rules functioning

---

administrator-manual/en/base_system.rst
administrator-manual/en/base_system2.rst
administrator-manual/en/chat.rst
administrator-manual/en/disaster_recovery.rst
administrator-manual/en/hotsync.rst
administrator-manual/en/index.rst
administrator-manual/en/mail.rst
administrator-manual/en/phone_home.rst
administrator-manual/en/team_chat.rst

Publish changes to stable branch

Update V7 branch

---

administrator-manual/en/upgrade_tool.rst

See also 
- https://github.com/NethServer/comps/pull/38
- https://github.com/nethesis/comps/pull/41
- https://community.nethserver.org/t/upgrade-tool-module/11112/29?u=davidep

Remove Upgrade Tool "Beta" wording

---

administrator-manual/en/hotsync.rst

Update hotsync documentation with new instructions.
@gsanchietti Could you review it?

Update HotSync documentation

---

administrator-manual/en/.gitignore
administrator-manual/en/.tx/config
administrator-manual/en/backup_customization.rst
administrator-manual/en/ftp.rst
administrator-manual/en/index.rst
administrator-manual/en/proxy_pass.rst
administrator-manual/en/virtual_hosts.rst
administrator-manual/en/web_server.rst

This is a new section entirely dedicated to the Web server cockpit app.
The PR also wants to introduce a new left menu section, for Cockpit Applications.

Web server application

---

administrator-manual/en/nextcloud.rst

Nextcloud 18

---

administrator-manual/en/mail.rst

Explain shared and public folders
Document SharedSeen dovecot prop

Add shared mailbox paragraph

---

administrator-manual/en/.tx/config
administrator-manual/en/index.rst
administrator-manual/en/mssql.rst

Added nethserver-mssql chapter to NethServer documentation.
Refer to https://github.com/NethServer/dev/issues/6078

docs. add nethserver-mssql chapter

---

administrator-manual/en/.tx/config
administrator-manual/en/blacklist.rst
administrator-manual/en/index.rst

See NethServer/dev#6072
Remember to push translations after merge

Threat shield doc

---

administrator-manual/en/dns.rst

dns: add domain redirection

---

administrator-manual/en/index.rst
administrator-manual/en/sandbox.rst

Add sandbox chapter

---

administrator-manual/en/base_system2.rst

Also add recovery codes for users

Describe 2FA for SSH

---

administrator-manual/en/locale/es/LC_MESSAGES/blacklist.po
administrator-manual/en/locale/es/LC_MESSAGES/launcher.po
administrator-manual/en/locale/it/LC_MESSAGES/blacklist.po
administrator-manual/en/locale/it/LC_MESSAGES/launcher.po

Add launcher and threat shield translations

Pull blacklist and launcher from transifex

---

administrator-manual/en/base_system2.rst

https://github.com/NethServer/dev/issues/6100

settings. added shell override and user-settings

---

administrator-manual/en/base_system2.rst

...Once "Override the shell of users" has been enabled
https://github.com/NethServer/dev/issues/6074
https://github.com/NethServer/dev/issues/6100

Document SSH&SFTP permissions

---

administrator-manual/en/bandwidth_monitor.rst
administrator-manual/en/dedalo.rst
administrator-manual/en/disaster_recovery.rst
administrator-manual/en/vpn.rst
administrator-manual/en/web_proxy.rst

Disaster recovery without network restore

---

administrator-manual/en/.tx/config
administrator-manual/en/locale/es/LC_MESSAGES/base_system2.po
administrator-manual/en/locale/es/LC_MESSAGES/disaster_recovery.po
administrator-manual/en/locale/es/LC_MESSAGES/dns.po
administrator-manual/en/locale/es/LC_MESSAGES/mail.po
administrator-manual/en/locale/es/LC_MESSAGES/mssql.po
administrator-manual/en/locale/es/LC_MESSAGES/nextcloud.po
administrator-manual/en/locale/es/LC_MESSAGES/sandbox.po
administrator-manual/en/locale/it/LC_MESSAGES/base_system2.po
administrator-manual/en/locale/it/LC_MESSAGES/disaster_recovery.po
administrator-manual/en/locale/it/LC_MESSAGES/dns.po
administrator-manual/en/locale/it/LC_MESSAGES/mail.po
administrator-manual/en/locale/it/LC_MESSAGES/mssql.po
administrator-manual/en/locale/it/LC_MESSAGES/nextcloud.po
administrator-manual/en/locale/it/LC_MESSAGES/sandbox.po

Add missing translations for:
- sandbox
- mssql

Translations

---

administrator-manual/en/access.rst
administrator-manual/en/access2.rst
administrator-manual/en/base_system.rst
administrator-manual/en/base_system2.rst
administrator-manual/en/index.rst
administrator-manual/en/pop3_proxy.rst

p3scan is now deprecated
NethServer/dev#6117

Hide pop3_proxy

---

administrator-manual/en/mssql.rst

Refer to https://github.com/federicoballarini/nethserver-business/issues/1

docs. add sqlcmd informations

---

administrator-manual/en/base_system2.rst
administrator-manual/en/fail2ban.rst
administrator-manual/en/vpn.rst

@gsanchietti I cannot push to nethserver doc...sorry it is a new PR proposal
```
git push upstream pr494:vpn_otp                 
remote: Permission to NethServer/docs.git denied to stephdl.
fatal: impossible d'accéder à 'https://github.com/NethServer/docs.git/' : The requested URL returned error: 403
```

vpn: describe otp authentication

---

administrator-manual/en/access2.rst
administrator-manual/en/base_system2.rst

Better describe changes from NS 7.8

Improve SSH and Server Manager access

---

administrator-manual/en/nscom_releases.rst
administrator-manual/en/release_notes.rst

New release notes for NS 7.8.2003.
Remember to add the real release date, when available.

Releases notes NethServer 7.8.2003

---

administrator-manual/en/access2.rst
administrator-manual/en/backup_customization.rst
administrator-manual/en/nscom_releases.rst
administrator-manual/en/release_notes.rst

Minor fixes from v7

---

administrator-manual/en/docker.rst
administrator-manual/en/index.rst

docker documentation to read the doc

Docker documentation

---

administrator-manual/en/tlspolicy.rst

https://github.com/NethServer/dev/issues/6170

TLS policy 2020-05-10

---

administrator-manual/en/docker.rst
administrator-manual/en/index.rst
administrator-manual/en/locale/es/LC_MESSAGES/release_notes.po
administrator-manual/en/locale/it/LC_MESSAGES/release_notes.po

Merge master to v7

---

administrator-manual/en/blacklist.rst

DNS blacklist documentation for Threat shield
https://github.com/NethServer/dev/issues/6212

Threat shield: DNS blacklist

---

administrator-manual/en/mail.rst

https://github.com/NethServer/dev/issues/6211

IMAP synchronization  based on imapsync

---

administrator-manual/en/blacklist.rst

Users will have a sample repository to test the DNS blacklist.
NethServer/dev#6212

blacklist: add sample DNS blacklist

---

administrator-manual/en/firewall.rst
administrator-manual/en/firewall2.rst

Documentation for new releases.
Refactor also original firewall page to improve readability.

Firewall: add live rules and mac objects

---

administrator-manual/en/disaster_recovery.rst

See https://community.nethserver.org/t/external-repository-not-restored-from-configuration-restore/16558

restore: document third-party repos

---

administrator-manual/en/index.rst
administrator-manual/en/shared_folder.rst

Shared folder page already describes the behavior of new Server Manager

Move shared folder page under Application sections

---

administrator-manual/en/accounts.rst
administrator-manual/en/base_system2.rst

Refs 
- https://github.com/NethServer/dev/issues/6320
- https://github.com/NethServer/docs/pull/536
After merging this PR, remember to complete this change https://github.com/NethServer/docs/pull/536#discussion_r516812285

Change the Users and groups page for Cockpit

---

administrator-manual/en/webtop5.rst

Additional note for custom virtual hosts on nextcloud

Update webtop5 docs

---

administrator-manual/en/firewall.rst

 New section "Settings" for the firewall chapter

---

administrator-manual/en/release_notes.rst

nDPI release notes

---

administrator-manual/en/base_system2.rst

@gsanchietti could you review the PR

Harden the SSH service with strong encryption

---

administrator-manual/en/hotsync.rst

Update HotSync section with an hint for November 2020 update.
Refer to https://github.com/NethServer/dev/issues/6335

docs. update hotsync section

---

administrator-manual/en/webtop5.rst

Aadditional note to view the custom logo

Additional note for custom logo

---

administrator-manual/en/web_proxy.rst

proxy: how to cleanup lightsquid reports

---

administrator-manual/en/index.rst

added link of the old version and italian version of Nethserver

Added link of the old version and italian version of Nethserver

---

administrator-manual/en/index.rst

Changed link for the old and the italian version of nethserver

Improve nsent links

---

administrator-manual/en/mail.rst

See https://github.com/NethServer/dev/issues/6446

Additional setup for mail GSSAPI auth

---

administrator-manual/en/blacklist.rst

blacklist: add geoip support

---

administrator-manual/en/collabora.rst

Documentation how to use CODE repository for collabora
https://github.com/NethServer/dev/issues/6490

CODE repository for collabora office

---

administrator-manual/en/disaster_recovery.rst

The note is valid for any UI and should be inside the
common section.
---
See https://community.nethserver.org/t/config-restore-do-not-restore-root-password/18471
Thanks to **pike**

restore: move root password note

---

administrator-manual/en/disaster_recovery.rst
administrator-manual/en/nsent/_static/nethesis.css
administrator-manual/en/registration.rst
administrator-manual/en/sandbox.rst

Merge into v7 branch

---

administrator-manual/en/webmail.rst

Note on how to change a skin in roundcubemail
https://github.com/NethServer/dev/issues/6541

Note on skins of roundcubemail

---

administrator-manual/en/mail.rst

Distribution groups are not supported

Fix group mailboxes

---

administrator-manual/en/webmail.rst

https://github.com/NethServer/dev/issues/6627

Documentation note about nethserver-roundcubemail-next

---

administrator-manual/en/nscom/requirements.txt
administrator-manual/en/nsent/requirements.txt

To avoid problems related to the UI the version of sphinx_rtd_theme goes from 0.5 to 1.0

Updated Sphinx_rtd_theme at the latest compatible version (#595)

---

administrator-manual/en/webtop5.rst

https://community.nethserver.org/t/webtop-configuration/19810

webtop: add external accounts section

---

administrator-manual/en/base_system2.rst
administrator-manual/en/vpn.rst

vpn: add OpenVPN mail notification
